name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Compile to binary
        run: CGO_ENABLED=0 GOOS=linux go build -o bin

      - name: Build a Docker image
        run: |
          docker stop go-dice-roller
          docker rm go-dice-roller
          docker build --tag go-dice-roller .

      - name: Run the Docker image
        run: docker run -d --name go-dice-roller --network nginx go-dice-roller:latest
