name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Compile to binary
        run: CGO_ENABLED=0 GOOS=linux go build -o bin

      - name: Build Docker image
        run: docker build --load --tag go-dice-roller .

      - name: Run Docker image
        uses: addnab/docker-run-action@v3
        with:
          image: go-dice-roller:latest
          network: nginx
