name: Deploy

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker buildx build --load --tag go-dice-roller .

      - name: Run Docker image
        uses: addnab/docker-run-action@v3
        with:
          image: go-dice-roller:latest
          network: nginx
